name = "sa-itinerary-worker"
main = "src/index.ts"
compatibility_date = "2024-07-25"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "serendipia_jobs_db"
database_id = "75f0b8a1-0e15-459a-8070-17091273e3dd"
